apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      name: firstdeployment 
      labels:
        color: blue #label this can be call in service
    spec:
      containers:
      - name: firstdeployment
        image: lakshmikar1993/nginx:myapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: firstserivce
spec:
  type: NodePort
  selector:
    color: blue #which was metion in above deployment ymal
  ports:
  - port: 80 #servic port
    targetPort: 80 # container port of nginx
    nodePort: 30032 #nodeport range 30000 to 32767
